-- No longer used for categories/settings: those are now per-user and seeded
-- automatically by the `on_auth_user_created` trigger (see
-- migrations/0002_auth.sql) the moment someone signs in with Google for the
-- first time. Nothing to run here after 0002.
